name: Run Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./A3

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    # --- CHANGE IS HERE ---
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest numpy scikit-learn matplotlib

    - name: Test with pytest
      run: |
        pytest