name: CI/CD Pipeline for Python Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # --- JOB 1: Test the code (Continuous Integration) ---
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./A3

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest numpy scikit-learn matplotlib

    - name: Test with pytest
      run: |
        pytest

  # --- JOB 2: "Deploy" the code (Continuous Deployment) ---
  deploy:
    # This job needs the 'build' job to succeed first
    needs: build
    runs-on: ubuntu-latest
    
    # Only run this job when pushing to the main branch, not on pull requests
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to production (simulation)
        run: echo "🚀 Deploying to production server..."