# Name for your GitHub Action workflow
name: Run Python Tests

# Trigger: Run this on every 'push' to the 'main' branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Jobs to run
jobs:
  build:
    # Use an Ubuntu virtual machine
    runs-on: ubuntu-latest

    steps:
    # 1. Check out your repository code
    - uses: actions/checkout@v3

    # 2. Set up a Python environment
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    # 3. Install the necessary Python libraries
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest numpy scikit-learn

    # 4. Run your tests using pytest
    - name: Test with pytest
      run: |
        pytest