name: CI/CD Pipeline for Python Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # --- JOB 1: Continuous Integration (tests) ---
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./A3
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"   # 3.10 is stable with most libs

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install pytest numpy scikit-learn matplotlib; fi

      - name: Run unit tests
        run: pytest -q

  # --- JOB 2: Continuous Deployment (Docker push) ---
  deploy:
    runs-on: ubuntu-latest
    needs: test
    # only push images on direct pushes to main, not on PRs
    if: ${{ needs.test.result == 'success' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push app image
        uses: docker/build-push-action@v6
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/a3-app:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/a3-app:${{ github.sha }}